### ISSUE TITLE
Enhance Terraform Support for Simultaneously Managing Shared and Assigned Repositories in Artifactory

### ISSUE THREAD

**Issue by borkke** [jfrog/terraform-provider-project#110]
**Is your feature request related to a problem? Please describe.**
It seems like I can't manage "shared" repositories together with “assigned” repositories and this is what I need to do. My TF state gets messed up.

**Describe the solution you'd like**
I would like to create remote repos for all public repos we use and share with all the projects (I need sharing here). 
Then, we plan to have ~10 projects and for each project we need many local repos assigned to a project and virtual also assigned to a project which contains local and the "shared remotes" (here I need assignments). All via Terraform. 

```
# I'm using "repos" as per the documentation
resource "project" "project" {
  key          = var.tla
  display_name = var.name
  .....
  # Not adding assignments yet on purpose
  repos = []

# 
resource "artifactory_remote_maven_repository" "mvn" {
  url = var.url
  key = var.name
  .....
  #ignoring bause I'm managing assignments via "project"
  #I coundn't find anything separate for "sharing" feature
  lifecycle {
    ignore_changes = [
      project_key
    ]
  }
}
```
Since I couldn't find an option to "share" via terraform, I went to the UI and shared it. Of course it starts to get messy. Even though I didn't use "assign to project" in the UI, I used "share", I'm seeing this change.
```
Terraform will perform the following actions:

  # module.onsite_project.project.project will be updated in-place
  ~ resource "project" "project" {
      ~ repos                      = [
          - "shared-docker-remote",
            # (1 unchanged element hidden)
        ]
    }
```
and then I get a message:
> Error: failed to update repos for project:
│ 404 DELETE https://jfrog.bestsecrettec.com/access/api/v1/projects/_/attach/repositories/shared-docker-remote
│ {
│   "errors" : [ {
│     "code" : "NOT_FOUND",
│     "message" : "Could not find resource `shared-docker-remote`; type `repo` in Projects configuration"
│   } ]
│ }

In the end, I think it would be a good idea to allow people to "share" repos on the repo level as part of the "artifactory_virtual_maven_repository" resource and leave the "repos = []" on the project level only for project assignments.

**Describe alternatives you've considered**
I was thinking to use the "project_key" in the repo to do the assignments (which is not suggested by the docs) and use lifecycle to ignore the "repos" on the project level. Then I have to share the repos manually via UI.

**Comment by alexhung** [comment]
@borkke So I think the issue is explained in [this community post](https://discuss.hashicorp.com/t/root-resource-was-present-but-now-absent-in-terraform/34047/5).

The project provider uses the [Projects API](https://jfrog.com/help/r/jfrog-rest-apis/move-repository-in-a-project) to assign a repository to a project during the "Create" part of the process. Before the end of this process, the provider set the resource ID to `<project-key>-<repo key>`.

Then the provider uses the [Artifactory Repository API](https://jfrog.com/help/r/jfrog-rest-apis/get-repositories) to read back the current state from the repository. This read process also set the same resource ID (because "Read" is also used for refresh and import). However, due to the nature of Artifactory internal working, the repository may not immediately has the latest state. This means the repository's `projectKey` field may be empty at the time of API request. I included this [logging statement](https://github.com/jfrog/terraform-provider-project/blob/master/pkg/project/resource_project_repository.go#L64) for this scenario. And you can find it in your logs.

This is an known issue and we have plan in Q2 to add new Projects API to retrieve the repo assignment status reliably.

In the meantime, I'll add retry logic to the "Read" process and have the provider to make a few (5?) attempts before giving up.

**Comment by borkke** [comment]
@alexhung good news! 
All cases I saw so far it succeeds after second tf apply - which means around 2-3 seconds. 

I guess if you put 1s timeout between attempts and fail after 5 attempts, I think it should be fine.

**Comment by alexhung** [comment]
@borkke The Terraform SDKv2 retry mechanism doesn't support number of retry or interval between retries, unfortunately. It will attempt the retry until timeout is reached, which for Creation is 20 min out of the box. I can potentially set it lower but probably unnecessary.
